// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace seinAppBackend.Models;

public partial class CuentasCobrar
{
    public int Id { get; set; }

    public int? Idcli { get; set; }

    public int? Idproducto { get; set; }

    public decimal? Avance { get; set; }

    public string Observacion { get; set; }

    public int? Estado { get; set; }

    public DateTime? Fecrea { get; set; }

    public int? Usercrea { get; set; }
}