// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace seinAppBackend.Models;

public partial class DataAppStore
{
    public int Id { get; set; }

    public string NombreAppStore { get; set; }

    public int? Usercrea { get; set; }

    public DateTime? Feccrea { get; set; }

    public string Observacion { get; set; }

    public int? Estado { get; set; }
}