// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace seinAppBackend.Models;

public partial class FilesSeason
{
    public int Id { get; set; }

    public string Url { get; set; }

    public DateTime? Fecrea { get; set; }

    public string Usercrea { get; set; }

    public string Codentity { get; set; }
}