// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace seinAppBackend.Models
{
    public partial class HistorialComprasResult
    {
        public int id { get; set; }
        public int? idusuario { get; set; }
        public int? idcliente { get; set; }
        public int? tienda { get; set; }
        public string nombreProducto { get; set; }
        public decimal? precioacliente { get; set; }
        public decimal? preciodeapp { get; set; }
        public string urlimagen { get; set; }
        public DateTime? fecrea { get; set; }
        public int? estado { get; set; }
        public string nombre { get; set; }
        public string email { get; set; }
        public int? edad { get; set; }
        public int? estadoUsuario { get; set; }
        public string direccion { get; set; }
        public string telefono { get; set; }
        public DateTime? fecreaUsuario { get; set; }
        public int? estadoTienda { get; set; }
        public DateTime? fereaTienda { get; set; }
        public string nombreAppStore { get; set; }
        public string observacionTienda { get; set; }
    }
}
