// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using seinAppBackend.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace seinAppBackend.Models
{
    public partial interface IsheinAppContextProcedures
    {
        Task<List<HistorialComprasResult>> HistorialComprasAsync(int? idUser, int? idCliente, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
