// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace seinAppBackend.Models;

public partial class Producto
{
    public int Id { get; set; }

    public int? Idusuario { get; set; }

    public int? Idcliente { get; set; }

    public int? Tienda { get; set; }

    public string NombreProducto { get; set; }

    public decimal? Precioacliente { get; set; }

    public decimal? Preciodeapp { get; set; }

    public string Urlimagen { get; set; }

    public DateTime? Fecrea { get; set; }

    public int? Estado { get; set; }
}