// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using seinAppBackend.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace seinAppBackend.Models
{
    public partial class sheinAppContext
    {
        private IsheinAppContextProcedures _procedures;

        public virtual IsheinAppContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new sheinAppContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IsheinAppContextProcedures GetProcedures()
        {
            return Procedures;
        }

        protected void OnModelCreatingGeneratedProcedures(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HistorialComprasResult>().HasNoKey().ToView(null);
        }
    }

    public partial class sheinAppContextProcedures : IsheinAppContextProcedures
    {
        private readonly sheinAppContext _context;

        public sheinAppContextProcedures(sheinAppContext context)
        {
            _context = context;
        }

        public virtual async Task<List<HistorialComprasResult>> HistorialComprasAsync(int? idUser, int? idCliente, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "idUser",
                    Value = idUser ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                new SqlParameter
                {
                    ParameterName = "idCliente",
                    Value = idCliente ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<HistorialComprasResult>("EXEC @returnValue = [dbo].[HistorialCompras] @idUser, @idCliente", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
